# Generated by Django 4.0.6 on 2022-08-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='disciplina',
            new_name='descricao',
        ),
    ]
